on:
  push:
    branches:
      - master 





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v3
      
        run: docker login --username ${{secrets.DOCKER}} --password ${{secrets.TOKEN}}
      
        
